In [24]:
# Importing Libraries 
import os, sys
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline 

import warnings
warnings.filterwarnings('always')
warnings.filterwarnings('ignore')


from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder

from statsmodels.stats.outliers_influence import variance_inflation_factor

In [25]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

target_column_name = 'Item_Outlet_Sales'
input_feature_train_df = train_df.drop(columns=[target_column_name],axis=1)
target_feature_train_df = train_df[target_column_name]

input_feature_test_df = test_df.drop(columns=[target_column_name],axis=1)
target_feature_test_df = test_df[target_column_name]


# function to get numerical and categorical columns 
def Numerical_categorical_column(dataframe):
    '''
    This function returns the numerical and categorical column 
    return numerical_columns,categorical_columns
    '''
    numerical_columns = [i for i in dataframe.columns if  dataframe[i].dtype != 'O']
    categorical_columns = [i for i in dataframe.columns if  dataframe[i].dtype == 'O']
    return numerical_columns,categorical_columns



#Replacing same values with different names 
input_feature_train_df['Item_Fat_Content'] = input_feature_train_df['Item_Fat_Content'].replace(['LF','low fat','reg'],['Low Fat','Low Fat','Regular'])
input_feature_test_df['Item_Fat_Content'] = input_feature_test_df['Item_Fat_Content'].replace(['LF','low fat','reg'],['Low Fat','Low Fat','Regular'])

#Removing unwanted data from name item_identifier
input_feature_train_df['Item_Identifier'] = input_feature_train_df['Item_Identifier'].apply(lambda x:x[:2])
input_feature_test_df['Item_Identifier'] = input_feature_test_df['Item_Identifier'].apply(lambda x:x[:2])

# Feature Engineering of Outlet Establishment year
input_feature_train_df['Outlet_age'] = 2013 - input_feature_train_df['Outlet_Establishment_Year']
input_feature_train_df.drop(columns=['Outlet_Establishment_Year'],inplace=True)

input_feature_test_df['Outlet_age'] = 2013 - test_df['Outlet_Establishment_Year']
input_feature_test_df.drop(columns=['Outlet_Establishment_Year'],inplace=True)

#Those product who are non-consumbale but have fat content will replace them with non-ediable fat content

input_feature_train_df.loc[input_feature_train_df['Item_Identifier']=='NC','Item_Fat_Content'] = 'Non Edible'
input_feature_test_df.loc[input_feature_test_df['Item_Identifier']=='NC','Item_Fat_Content'] = 'Non Edible'


# dropping unwanted columns will work on it after some time 
input_feature_train_df.drop(columns=['Item_Type','Outlet_Identifier'],inplace = True)
input_feature_test_df.drop(columns=['Item_Type','Outlet_Identifier'],inplace = True)

numerical_features,categorical_features = Numerical_categorical_column(input_feature_train_df)


# Piepline for Numerical Columns 
from sklearn.pipeline import Pipeline
num_pipeline = Pipeline(steps=[
    ('imputer',KNNImputer(n_neighbors=3, weights='uniform',missing_values=np.nan)),
    ('scaler',StandardScaler())
])


cat_pipeline = Pipeline(steps=[
    ('imputer',KNNImputer(n_neighbors=3, weights='uniform',missing_values=np.nan)),
    ('scaler',StandardScaler())
])



from sklearn.compose import ColumnTransformer
preprocessing = ColumnTransformer([
                ('num_pipeline', num_pipeline, numerical_features),
                ('cat_pipeline', cat_pipeline, categorical_features),
            ])

train_num_df = input_feature_train_df[numerical_features]
train_cat_df = input_feature_train_df[categorical_features]
train_cat_df = train_cat_df.apply(LabelEncoder().fit_transform)
train_cat_df['Outlet_Size'].replace(3,np.nan,inplace=True)

test_num_df = input_feature_test_df[numerical_features]
test_cat_df = input_feature_test_df[categorical_features]
test_cat_df = test_cat_df .apply(LabelEncoder().fit_transform)
test_cat_df['Outlet_Size'].replace(3,np.nan,inplace=True)

input_feature_train_df = pd.concat([train_num_df,train_cat_df],axis=1)
input_feature_test_df = pd.concat([test_num_df,test_cat_df],axis=1)


train_array = preprocessing.fit_transform(input_feature_train_df)
input_feature_train_df = pd.DataFrame(train_array,columns=input_feature_train_df.columns)
input_feature_train_df



test_array = preprocessing.transform(input_feature_test_df)
input_feature_test_df = pd.DataFrame(test_array,columns=input_feature_test_df.columns)
input_feature_test_df

,Item_Weight,Item_Visibility,Item_MRP,Outlet_age,Item_Identifier,Item_Fat_Content,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,1.798914,-1.135138,-0.532035,-0.139541,-0.179795,-0.997813,-0.429154,-1.369334,-0.252658
1,-1.047131,-0.536960,-0.861920,-1.095190,-0.179795,1.236942,0.898016,-0.138882,-0.252658
2,0.393036,0.648183,1.618094,-0.020085,1.735696,0.119565,-1.756324,1.091569,-1.508289
3,-1.272300,-0.983503,0.225484,-1.095190,-0.179795,-0.997813,0.898016,-0.138882,-0.252658
4,0.186917,1.016910,1.497272,1.532846,-0.179795,1.236942,-0.429154,1.091569,2.258603
...,...,...,...,...,...,...,...,...,...
5676,-0.544215,-1.020172,0.005181,0.099372,-0.179795,1.236942,0.898016,-1.369334,-0.252658
5677,-1.207149,1.489663,0.452086,-1.334103,-0.179795,1.236942,-0.429154,1.091569,1.002972
5678,-0.658514,0.143358,-0.357287,-0.497909,1.735696,0.119565,0.898016,-0.138882,-0.252658
5679,0.553055,-1.281758,1.182389,-1.095190,-0.179795,1.236942,0.898016,-0.138882,-0.252658
5680,-0.772813,0.747907,-0.982743,-0.497909,-0.179795,1.236942,0.898016,-0.138882,-0.252658

In [26]:
import joblib

joblib.dump(preprocessing,'processord.pkl')

['processord.pkl']

In [27]:
preprocessingf = joblib.load('processord.pkl')

In [29]:
numerical_features

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_age']

In [30]:
categorical_features

['Item_Identifier',
 'Item_Fat_Content',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type']

In [32]:
t = pd.read_csv(r"D:\Projects_new\Stores_Sales_Prediction\sales\artifact\data_transformation\2022-07-24-20-07-36\preprocessed_files\train_transformed\train.csv")

In [33]:
t

,Unnamed: 0,Item_Weight,Item_Visibility,Item_MRP,Outlet_age,Item_Identifier,Item_Fat_Content,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,0,-0.818533,-0.970732,1.747454,-0.139541,-0.179795,-0.997813,-0.429154,-1.369334,-0.252658
1,1,-1.591194,-0.908111,-1.489023,-1.334103,-2.095286,1.236942,-0.429154,1.091569,1.002972
2,2,1.055970,-0.956917,0.010040,-0.139541,-0.179795,-0.997813,-0.429154,-1.369334,-0.252658
3,3,1.444587,-1.281758,0.660050,-0.020085,-0.179795,1.236942,-1.756324,1.091569,-1.508289
4,4,-0.903114,-1.281758,-1.399220,1.293934,1.735696,0.119565,-1.756324,1.091569,-0.252658
...,...,...,...,...,...,...,...,...,...,...
8518,8518,-1.375169,-0.181193,1.180783,1.293934,-0.179795,-0.997813,-1.756324,1.091569,-0.252658
8519,8519,-1.028843,-0.371154,-0.527301,-0.497909,-0.179795,1.236942,0.898016,-0.138882,-0.252658
8520,8520,-0.521356,-0.599784,-0.897208,-0.736822,1.735696,0.119565,0.898016,-0.138882,-0.252658
8521,8521,-1.296303,1.532880,-0.607977,-1.334103,-0.179795,1.236942,-0.429154,1.091569,1.002972
8522,8522,0.438756,-0.411936,-1.052261,0.099372,-2.095286,-0.997813,0.898016,-1.369334,-0.252658

In [34]:
input_feature_train_df

,Item_Weight,Item_Visibility,Item_MRP,Outlet_age,Item_Identifier,Item_Fat_Content,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,-0.818533,-0.970732,1.747454,-0.139541,-0.179795,-0.997813,-0.429154,-1.369334,-0.252658
1,-1.591194,-0.908111,-1.489023,-1.334103,-2.095286,1.236942,-0.429154,1.091569,1.002972
2,1.055970,-0.956917,0.010040,-0.139541,-0.179795,-0.997813,-0.429154,-1.369334,-0.252658
3,1.444587,-1.281758,0.660050,-0.020085,-0.179795,1.236942,-1.756324,1.091569,-1.508289
4,-0.903114,-1.281758,-1.399220,1.293934,1.735696,0.119565,-1.756324,1.091569,-0.252658
...,...,...,...,...,...,...,...,...,...
8518,-1.375169,-0.181193,1.180783,1.293934,-0.179795,-0.997813,-1.756324,1.091569,-0.252658
8519,-1.028843,-0.371154,-0.527301,-0.497909,-0.179795,1.236942,0.898016,-0.138882,-0.252658
8520,-0.521356,-0.599784,-0.897208,-0.736822,1.735696,0.119565,0.898016,-0.138882,-0.252658
8521,-1.296303,1.532880,-0.607977,-1.334103,-0.179795,1.236942,-0.429154,1.091569,1.002972
8522,0.438756,-0.411936,-1.052261,0.099372,-2.095286,-0.997813,0.898016,-1.369334,-0.252658